<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit1e96855b80cdc4779a2be76b83377c6d
{
    public static $prefixLengthsPsr4 = array (
        'C' => 
        array (
            'CustomShippingZones\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'CustomShippingZones\\' => 
        array (
            0 => __DIR__ . '/../..' . '/includes',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit1e96855b80cdc4779a2be76b83377c6d::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit1e96855b80cdc4779a2be76b83377c6d::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit1e96855b80cdc4779a2be76b83377c6d::$classMap;

        }, null, ClassLoader::class);
    }
}
